name: Maven Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Increment project version
        run: |
          cd JDK11/opentraceability
          mvn versions:set -DnewVersion=${{ github.sha }}

      - name: Build and test
        run: |
          cd JDK11/opentraceability
          mvn clean verify

      - name: Deploy to Maven
        run: |
          cd JDK11/opentraceability
          mvn deploy --settings settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
